# GitHub Actions workflow文件
name: Update HSR Download Info

on:
  schedule:
    - cron:  '0 6 * * *' # runs at each hour

  workflow_dispatch: # This allows manual trigger.

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo content
        uses: actions/checkout@v4.1.1 # checkout the repository content to github runner.
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token.
          fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.
      - name: Setup python
        uses: actions/setup-python@v5.0.0
        with:
          python-version: '3.12' # install the python version needed
      - name: Install python packages
        run: |
          python -m pip install --upgrade pip
          pip install requests
      - name: Run python script
        run: |
          python HSR_API.py
      - name: Commit files
        run: |
          git config --local user.email "SK_HansonX@outlook.com"
          git config --local user.name "LtgX"
          git add README.md
          git add history/*
          git commit -m "Update files"
      - name: Push
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.MY_GIT_TOKEN }}
          branch: main
